### ISSUE TITLE
Download button not working in some conditions

### ISSUE THREAD

**Issue by sdtaheri** [mxcl/Workbench#21]
Thanks for this awesome app. 
I found out that when there’s a conflict between locally stored file and the remote version, the download button would not do anything. I don’t know if it’s unable to replace the local file with the remote version or it fails to download the remote version.

**Comment by mxcl** [comment]
My bad, I didn't fill this in before releasing. Will fix.

**Comment by mxcl** [comment]
Fixed in 1.0.3. You can force an update holding ⌥ and clicking the cog button.

**Comment by sdtaheri** [comment]
Thanks for this fast fix.
