### ISSUE TITLE
Exception in notification on launch

### ISSUE THREAD

**Issue by machawk1** [mxcl/Workbench#23]
I downloaded the 1.0.5 release and launched the .app. When I do so, I immediately get a macOS 10.14.3 notification.

![screen shot 2019-03-05 at 10 53 19 am](https://user-images.githubusercontent.com/2514780/53818117-952bc100-3f35-11e9-86f9-1d15baff7c3d.png)

As a caveat, I don't use iCloud:

![screen shot 2019-03-05 at 10 56 25 am](https://user-images.githubusercontent.com/2514780/53818126-99f07500-3f35-11e9-9ae0-6fed53d56709.png)

...but was interested in [your tweet](https://twitter.com/mxcl/status/1102947611227684864) relating to homebrew integration.

**Comment by mxcl** [comment]
Brew integration is in the next release (not yet released). I will endeavor to make the Dotfile sync portion deactivate gracefully for this use-case. Thanks!

**Comment by machawk1** [comment]
@mxcl I am looking forward to the homebrew integration and expected it to not necessarily be available in 1.0.5, since the screenshot in the tweet says 1.0.6.

It was not clear that the exception reported in the above screenshot related to #9 re:Detecting if iCloud is off.

**Comment by mxcl** [comment]
> I am looking forward to the homebrew integration and expected it to not necessarily be available in 1.0.5, since the screenshot in the tweet says 1.0.6.

The integration is light currently, but I plan to flesh it out.

> It was not clear that the exception reported in the above screenshot related to #9 re:Detecting if iCloud is off.

Yeah np, I understand that only I really know what's going on my ticket trackers.

**Comment by mxcl** [comment]
1.0.6 released, LMK if it isn’t fixed, I didn't try turning iCloud off as it can be quite disastrous.

**Comment by machawk1** [comment]
@mxcl I downloaded the 1.0.6 release and no longer receive the aforementioned Unexpected Error notification. I now see the `brew` tab and do not use iCloud, so will experiment with the former. Thanks for the quick response.
