### ISSUE TITLE
Dark footer difficult to read against light wallpaper

### ISSUE THREAD

**Issue by mklbtz** [mxcl/Workbench#24]
The contrast and legibiliity of the text and buttons is pretty poor in dark mode when used against a light background. 

![screen shot 2019-03-05 at 11 19 56 am](https://user-images.githubusercontent.com/1493623/53819950-ebe6ca00-3f38-11e9-8085-fe454b8fa07a.png)

In light mode, though, everything is perfectly legible. 

![screen shot 2019-03-05 at 11 19 48 am](https://user-images.githubusercontent.com/1493623/53819990-facd7c80-3f38-11e9-8b39-b9004b0b2b92.png)

Any improvement on the legibility would be appreciated, though I'm not sure how configurable these things from AppKit are. Thank you for all your hard work!

**Comment by mxcl** [comment]
Yeah, I’ve noticed this, but am not sure how to fix it.

**Comment by mxcl** [comment]
<img width="459" alt="screen shot 2019-03-05 at 12 10 55 pm" src="https://user-images.githubusercontent.com/58962/53823416-be514f00-3f3f-11e9-872a-ffb56ea8f2d6.png">

Fixed in upcoming 1.0.7 release.
