### ISSUE TITLE
Conflict files can not be uploaded, downloaded or even removed

### ISSUE THREAD

**Issue by jeffreylyg** [mxcl/Workbench#25]
Version 1.0.7

**Comment by mxcl** [comment]
Did you try restarting the app? May be a work-around for now. Sorry for the bug, I haven’t yet experienced it. Will work on a proper fix.

**Comment by jeffreylyg** [comment]
> Did you try restarting the app? May be a work-around for now. Sorry for the bug, I haven’t yet experienced it. Will work on a proper fix.

Yeah，I have tried restarting the app and even restarting my computer.
That's OK. This is an awesome work. Thanks for you hard work all the same. :)

**Comment by mxcl** [comment]
Hmm damn, sorry.

**Comment by mxcl** [comment]
Upload/Download fixed. Didn’t try `remove` though, is that also broken then?

**Comment by jeffreylyg** [comment]
> Upload/Download fixed (1.0.9). Didn’t try `remove` though, is that also broken then?

Awesome, it worked. I use 1.0.9 override the old one.
