### ISSUE TITLE
Workbench has forgotten which files are stored and errors on trying to readd them.

### ISSUE THREAD

**Issue by jasikpark** [mxcl/Workbench#27]
So if I run "Add default files" for each file it shows this pop-up:

<img width="532" alt="Screenshot 2019-03-28 16 51 23" src="https://user-images.githubusercontent.com/10626596/55195210-d81a3680-5179-11e9-8148-ffddeddb21f7.png">

Which apparently at some point it's gotten confused about what actually *is* uploaded to iCloud but it can't use that error to redownload them?

**Comment by jasikpark** [comment]
Also THANK YOU FOR MAKING THIS IT IS AMAZING. forgot to add that.

**Comment by mxcl** [comment]
This is pretty odd, we ask for all records so if it’s there it should show up. I have no immediate ideas.

Probably you can fix it by deleting your iCloud for Workbench. I forget where you go to do that though.

**Comment by jasikpark** [comment]
Hmmm... idk either. I'll research that but I'm not sure how successful I'll be. Thanks!

**Comment by mxcl** [comment]
There's a way, I believe.

I cannot personally do anything. CloudKit databases are yours and only yours. I could if necessary make a new build with a reset button though.

**Comment by jasikpark** [comment]
I think it might be best to try that? I can't find anything anywhere about users being able to manage per-app data on macOS. For iPhone it's simple but apparently much more confusing w/ macOS

Unless if you have seen anything.

**Comment by jasikpark** [comment]
Or it's just magically resolved itself now. More transparency and the ability to do something like git merge might be good though -- at least being able to view the remote and local files side by side before blindly uploading or downloading one or the other.

**Comment by mxcl** [comment]
There’s plenty that can be done with the tool for sure. PRs welcome until I get round to it.
