### ISSUE TITLE
Similar(ish) project to be aware of?

### ISSUE THREAD

**Issue by jasikpark** [mxcl/Workbench#29]
https://github.com/alichtman/shallow-backup 

The one thing I really appreciate about Workbench is that it bypasses the privacy problem. It is sad that it's not cross-platform or cross-mac but it is good.

**Comment by alichtman** [comment]
Hey, this is a sweet project! Nice work!

One feature that `shallow-backup` is really missing is the GUI. This project nails that. 

Unfortunately, the fact that it's not cross-platform makes this not suitable for my needs. This was one of the reasons that I wrote `shallow-backup` in the first place.

**Comment by mxcl** [comment]
There's plenty of similar tools, I didn't like any of them so I released this, if you like another better, than please use it. Thanks.
